- name: extraswap set swap_file variable
  set_fact:
    swap_file: /extraswap

- name: extraswap check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: extraswap create swap file
  command: dd if=/dev/zero of={{ swap_file }} bs=1M count=1024
  when: not swap_file_check.stat.exists

- name: extraswap set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: extraswap format swap file
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: extraswap add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} swap swap defaults,pri=0 0 0"

- name: extraswap turn on swap
  command: swapon -a

- name: extraswap set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
