- name: Include Vault vars
  include_vars: "vault_vars/aws"

- cloudformation:
    stack_name: "{{  stack_name  }}"
    state: "present"
    disable_rollback: true
    region: "{{ aws.aws_region_name }}"
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    template: roles/aws_cf/files/cloudformation.json
    template_parameters:
      KeyName: "{{ aws.ec2_key_name }}"
      InstanceType: "t2.nano"
    tags:
      Stack: "{{  stack_name  }}"

- ec2_remote_facts:
    region: "{{ aws.aws_region_name }}"
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    filters:
      "tag:Stack": "{{  stack_name  }}"
      "tag:Role": "openvpn-server"
      "instance-state-name": "running"
  register: ec2

- debug: msg="{{ item['public_ip_address'] }}"
  with_items: "{{ ec2.instances }}"

- add_host:
    name: "vpn_{{ aws.aws_region_name }}_{{ item.0 }}.tld"
    ansible_host: "{{ item.1['public_ip_address'] }}"
    groupname: "openvpn"
  with_indexed_items: "{{ ec2.instances }}"

- wait_for:
    host: "{{ item.public_ip_address }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
