---

- name: SRV create openvpn key directory
  file: path=/etc/openvpn/keys state=directory

- name: SRV generate CA key
  command: openssl req -nodes -newkey rsa:4096 -keyout ca-key.pem -out ca-csr.pem -days 3650 -subj /CN=OpenVPN-CA/
    chdir=/etc/openvpn/keys
    creates=ca-key.pem

- name: SRV sign CA key
  command: openssl x509 -req -in ca-csr.pem -out ca.crt -CAcreateserial -signkey ca-key.pem -days 3650
    chdir=/etc/openvpn/keys
    creates=ca.crt

- name: SRV generate server key
  command: openssl req -nodes -newkey rsa:4096 -keyout server.key -out server.csr -days 3650 -subj /CN=OpenVPN/
    chdir=/etc/openvpn/keys
    creates=server.key

- name: SRV fix file permisions server.key
  file:
    path: /etc/openvpn/keys/server.key
    mode: 0640

- name: SRV generate CA serial
  copy:
    content: "01"
    dest: /etc/openvpn/keys/ca.srl
    force: no

- name: SRV copy openssl server extension config
  copy: src=openssl-server.ext dest=/etc/openvpn/keys owner=root group=root mode=0400

- name: SRV sign server key
  command: openssl x509 -req -in server.csr -out server.crt -CA ca.crt -CAkey ca-key.pem -days 3650 -extfile openssl-server.ext
  args:
    chdir:   /etc/openvpn/keys
    creates: server.crt

- name: SRV generate tls-auth key
  command: openvpn --genkey --secret ta.key
  args:
    chdir:   /etc/openvpn/keys
    creates: ta.key

- name: SRV generate DHparam
  command: openssl dhparam -dsaparam -out dh4096.pem 4096
  args:
    chdir:   /etc/openvpn/keys
    creates: dh4096.pem